export const AttachmentError = {
  FORBIDDEN: "FORBIDDEN",
  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  UNSUPPORTED_TYPE: "UNSUPPORTED_TYPE",
  NO_FILE: "NO_FILE",
  FILENAME_TOO_LONG: "FILENAME_TOO_LONG",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;
export type AttachmentError = (typeof AttachmentError)[keyof typeof AttachmentError];
