export const BoardError = {
  FORBIDDEN: "FORBIDDEN",
  BOARD_NOT_FOUND: "BOARD_NOT_FOUND",
  COLUMN_NOT_FOUND: "COLUMN_NOT_FOUND",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CANNOT_GRANT_OWNER: "CANNOT_GRANT_OWNER",
  CANNOT_GRANT_SELF: "CANNOT_GRANT_SELF",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  INVALID_MOVE: "INVALID_MOVE",
  INVALID_DUE_RANGE: "INVALID_DUE_RANGE",
  PARENT_ARCHIVED: "PARENT_ARCHIVED",
} as const;
export type BoardError = (typeof BoardError)[keyof typeof BoardError];
